services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment: 
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: skinet 
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  mysql-data:
